[package]
name = "sf"
version = "0.1.0"
authors = ["ky <pupupu0701@gmail.com>"]
edition = "2018"

[dev-dependencies]
tempfile = "3.2.0"

[dependencies]
structopt = "0.3.22"
uuid = { version = "0.8", features = ["serde", "v4"] }
pbr = "1.0.4"
regex = "1.4.3"
